//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.15 at 05:51:24 PM KRAT 
//


package domain;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZGLV">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="DATA" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="MONTH" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DAY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="SMO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IRP">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="N_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IRP_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DATE_CREATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="TIME_CREATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="WAY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="HOW" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="THEME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OTV_T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="OTV_KON" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EMPLOYEE_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Z_SV">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ADR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="E-MAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IN_SV">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DATA_PLAN" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="DATE_CLOSE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="RESULT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zglv",
    "irp"
})
@XmlRootElement(name = "IRP_LIST")
public class IRPLIST {

    @XmlElement(name = "ZGLV", required = true)
    protected IRPLIST.ZGLV zglv;
    //@XmlElement(name = "IRP", required = true)
    //protected IRPLIST.IRP irp;
    @XmlElement(name = "IRP", required = true)
    private ArrayList<IRPLIST.IRP> irp;

    /**
     * Gets the value of the zglv property.
     * 
     * @return
     *     possible object is
     *     {@link IRPLIST.ZGLV }
     *     
     */
    public IRPLIST.ZGLV getZGLV() {
        return zglv;
    }

    /**
     * Sets the value of the zglv property.
     * 
     * @param value
     *     allowed object is
     *     {@link IRPLIST.ZGLV }
     *     
     */
    public void setZGLV(IRPLIST.ZGLV value) {
        this.zglv = value;
    }

    /**
     * Gets the value of the irp property.
     * 
     * @return
     *     possible object is
     *     {@link IRPLIST.IRP }
     *     
     */
    public ArrayList<IRPLIST.IRP> getIRP() {
        return irp;
    }

    /**
     * Sets the value of the irp property.
     * 
     * @param value
     *     allowed object is
     *     {@link IRPLIST.IRP }
     *     
     */
    public void setIRP(ArrayList<IRPLIST.IRP> value) {
        this.irp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="N_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IRP_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="DATE_CREATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="TIME_CREATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="WAY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="HOW" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="THEME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OTV_T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="OTV_KON" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EMPLOYEE_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Z_SV">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ADR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="E-MAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IN_SV">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DATA_PLAN" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="DATE_CLOSE" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="RESULT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ntype",
        "irptype",
        "datecreate",
        "timecreate",
        "way",
        "how",
        "theme",
        "otvt",
        "otvkon",
        "employee1",
        "zsv",
        "insv",
        "dataplan",
        "dateclose",
        "result"
    })
    public static class IRP {

        @XmlElement(name = "N_TYPE", required = true)
        protected String ntype;
        @XmlElement(name = "IRP_TYPE")
        protected byte irptype;
        @XmlElement(name = "DATE_CREATE", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datecreate;
        @XmlElement(name = "TIME_CREATE", required = true)
        protected String timecreate;
        @XmlElement(name = "WAY")
        protected byte way;
        @XmlElement(name = "HOW")
        protected byte how;
        @XmlElement(name = "THEME", required = true)
        protected String theme;
        @XmlElement(name = "OTV_T")
        protected byte otvt;
        @XmlElement(name = "OTV_KON")
        protected int otvkon;
        @XmlElement(name = "EMPLOYEE_1", required = true)
        protected String employee1;
        @XmlElement(name = "Z_SV", required = true)
        protected IRPLIST.IRP.ZSV zsv;
        @XmlElement(name = "IN_SV", required = true)
        protected IRPLIST.IRP.INSV insv;
        @XmlElement(name = "DATA_PLAN", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataplan;
        @XmlElement(name = "DATE_CLOSE", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateclose;
        @XmlElement(name = "RESULT")
        protected byte result;

        /**
         * Gets the value of the ntype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNTYPE() {
            return ntype;
        }

        /**
         * Sets the value of the ntype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNTYPE(String value) {
            this.ntype = value;
        }

        /**
         * Gets the value of the irptype property.
         * 
         */
        public byte getIRPTYPE() {
            return irptype;
        }

        /**
         * Sets the value of the irptype property.
         * 
         */
        public void setIRPTYPE(byte value) {
            this.irptype = value;
        }

        /**
         * Gets the value of the datecreate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATECREATE() {
            return datecreate;
        }

        /**
         * Sets the value of the datecreate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATECREATE(XMLGregorianCalendar value) {
            this.datecreate = value;
        }

        /**
         * Gets the value of the timecreate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTIMECREATE() {
            return timecreate;
        }

        /**
         * Sets the value of the timecreate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTIMECREATE(String value) {
            this.timecreate = value;
        }

        /**
         * Gets the value of the way property.
         * 
         */
        public byte getWAY() {
            return way;
        }

        /**
         * Sets the value of the way property.
         * 
         */
        public void setWAY(byte value) {
            this.way = value;
        }

        /**
         * Gets the value of the how property.
         * 
         */
        public byte getHOW() {
            return how;
        }

        /**
         * Sets the value of the how property.
         * 
         */
        public void setHOW(byte value) {
            this.how = value;
        }

        /**
         * Gets the value of the theme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTHEME() {
            return theme;
        }

        /**
         * Sets the value of the theme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTHEME(String value) {
            this.theme = value;
        }

        /**
         * Gets the value of the otvt property.
         * 
         */
        public byte getOTVT() {
            return otvt;
        }

        /**
         * Sets the value of the otvt property.
         * 
         */
        public void setOTVT(byte value) {
            this.otvt = value;
        }

        /**
         * Gets the value of the otvkon property.
         * 
         */
        public int getOTVKON() {
            return otvkon;
        }

        /**
         * Sets the value of the otvkon property.
         * 
         */
        public void setOTVKON(int value) {
            this.otvkon = value;
        }

        /**
         * Gets the value of the employee1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMPLOYEE1() {
            return employee1;
        }

        /**
         * Sets the value of the employee1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMPLOYEE1(String value) {
            this.employee1 = value;
        }

        /**
         * Gets the value of the zsv property.
         * 
         * @return
         *     possible object is
         *     {@link IRPLIST.IRP.ZSV }
         *     
         */
        public IRPLIST.IRP.ZSV getZSV() {
            return zsv;
        }

        /**
         * Sets the value of the zsv property.
         * 
         * @param value
         *     allowed object is
         *     {@link IRPLIST.IRP.ZSV }
         *     
         */
        public void setZSV(IRPLIST.IRP.ZSV value) {
            this.zsv = value;
        }

        /**
         * Gets the value of the insv property.
         * 
         * @return
         *     possible object is
         *     {@link IRPLIST.IRP.INSV }
         *     
         */
        public IRPLIST.IRP.INSV getINSV() {
            return insv;
        }

        /**
         * Sets the value of the insv property.
         * 
         * @param value
         *     allowed object is
         *     {@link IRPLIST.IRP.INSV }
         *     
         */
        public void setINSV(IRPLIST.IRP.INSV value) {
            this.insv = value;
        }

        /**
         * Gets the value of the dataplan property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATAPLAN() {
            return dataplan;
        }

        /**
         * Sets the value of the dataplan property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATAPLAN(XMLGregorianCalendar value) {
            this.dataplan = value;
        }

        /**
         * Gets the value of the dateclose property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATECLOSE() {
            return dateclose;
        }

        /**
         * Sets the value of the dateclose property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATECLOSE(XMLGregorianCalendar value) {
            this.dateclose = value;
        }

        /**
         * Gets the value of the result property.
         * 
         */
        public byte getRESULT() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         */
        public void setRESULT(byte value) {
            this.result = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zi",
            "zf",
            "zo",
            "zdr",
            "zenp",
            "zsmo",
            "zdoctype",
            "zdocser",
            "zdocnum"
        })
        public static class INSV {

            @XmlElement(name = "Z_I", required = true)
            protected String zi;
            @XmlElement(name = "Z_F", required = true)
            protected String zf;
            @XmlElement(name = "Z_O", required = true)
            protected String zo;
            @XmlElement(name = "Z_DR", required = true)
            protected String zdr;
            @XmlElement(name = "Z_ENP", required = true)
            protected String zenp;
            @XmlElement(name = "Z_SMO", required = true)
            protected String zsmo;
            @XmlElement(name = "Z_DOCTYPE", required = true)
            protected String zdoctype;
            @XmlElement(name = "Z_DOCSER", required = true)
            protected String zdocser;
            @XmlElement(name = "Z_DOCNUM", required = true)
            protected String zdocnum;

            /**
             * Gets the value of the zi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZI() {
                return zi;
            }

            /**
             * Sets the value of the zi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZI(String value) {
                this.zi = value;
            }

            /**
             * Gets the value of the zf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZF() {
                return zf;
            }

            /**
             * Sets the value of the zf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZF(String value) {
                this.zf = value;
            }

            /**
             * Gets the value of the zo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZO() {
                return zo;
            }

            /**
             * Sets the value of the zo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZO(String value) {
                this.zo = value;
            }

            /**
             * Gets the value of the zdr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDR() {
                return zdr;
            }

            /**
             * Sets the value of the zdr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDR(String value) {
                this.zdr = value;
            }

            /**
             * Gets the value of the zenp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZENP() {
                return zenp;
            }

            /**
             * Sets the value of the zenp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZENP(String value) {
                this.zenp = value;
            }

            /**
             * Gets the value of the zsmo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZSMO() {
                return zsmo;
            }

            /**
             * Sets the value of the zsmo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZSMO(String value) {
                this.zsmo = value;
            }

            /**
             * Gets the value of the zdoctype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCTYPE() {
                return zdoctype;
            }

            /**
             * Sets the value of the zdoctype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCTYPE(String value) {
                this.zdoctype = value;
            }

            /**
             * Gets the value of the zdocser property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCSER() {
                return zdocser;
            }

            /**
             * Sets the value of the zdocser property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCSER(String value) {
                this.zdocser = value;
            }

            /**
             * Gets the value of the zdocnum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCNUM() {
                return zdocnum;
            }

            /**
             * Sets the value of the zdocnum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCNUM(String value) {
                this.zdocnum = value;
            }

			@Override
			public String toString() {
				StringBuilder builder = new StringBuilder();
				builder.append("INSV [zi=");
				builder.append(zi);
				builder.append(", zf=");
				builder.append(zf);
				builder.append(", zo=");
				builder.append(zo);
				builder.append(", zdr=");
				builder.append(zdr);
				builder.append(", zenp=");
				builder.append(zenp);
				builder.append(", zsmo=");
				builder.append(zsmo);
				builder.append(", zdoctype=");
				builder.append(zdoctype);
				builder.append(", zdocser=");
				builder.append(zdocser);
				builder.append(", zdocnum=");
				builder.append(zdocnum);
				builder.append("]");
				return builder.toString();
			}

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Z_I" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_F" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_O" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_ENP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_SMO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCSER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Z_DOCNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ADR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="E-MAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zi",
            "zf",
            "zo",
            "zdr",
            "zenp",
            "zsmo",
            "zdoctype",
            "zdocser",
            "zdocnum",
            "adr",
            "phone",
            "email"
        })
        public static class ZSV {

            @XmlElement(name = "Z_I", required = true)
            protected String zi;
            @XmlElement(name = "Z_F", required = true)
            protected String zf;
            @XmlElement(name = "Z_O", required = true)
            protected String zo;
            @XmlElement(name = "Z_DR", required = true)
            protected String zdr;
            @XmlElement(name = "Z_ENP", required = true)
            protected String zenp;
            @XmlElement(name = "Z_SMO", required = true)
            protected String zsmo;
            @XmlElement(name = "Z_DOCTYPE", required = true)
            protected String zdoctype;
            @XmlElement(name = "Z_DOCSER", required = true)
            protected String zdocser;
            @XmlElement(name = "Z_DOCNUM", required = true)
            protected String zdocnum;
            @XmlElement(name = "ADR", required = true)
            protected String adr;
            @XmlElement(name = "PHONE", required = true)
            protected String phone;
            @XmlElement(name = "E-MAIL", required = true)
            protected String email;

            /**
             * Gets the value of the zi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZI() {
                return zi;
            }

            /**
             * Sets the value of the zi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZI(String value) {
                this.zi = value;
            }

            /**
             * Gets the value of the zf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZF() {
                return zf;
            }

            /**
             * Sets the value of the zf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZF(String value) {
                this.zf = value;
            }

            /**
             * Gets the value of the zo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZO() {
                return zo;
            }

            /**
             * Sets the value of the zo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZO(String value) {
                this.zo = value;
            }

            /**
             * Gets the value of the zdr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDR() {
                return zdr;
            }

            /**
             * Sets the value of the zdr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDR(String value) {
                this.zdr = value;
            }

            /**
             * Gets the value of the zenp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZENP() {
                return zenp;
            }

            /**
             * Sets the value of the zenp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZENP(String value) {
                this.zenp = value;
            }

            /**
             * Gets the value of the zsmo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZSMO() {
                return zsmo;
            }

            /**
             * Sets the value of the zsmo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZSMO(String value) {
                this.zsmo = value;
            }

            /**
             * Gets the value of the zdoctype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCTYPE() {
                return zdoctype;
            }

            /**
             * Sets the value of the zdoctype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCTYPE(String value) {
                this.zdoctype = value;
            }

            /**
             * Gets the value of the zdocser property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCSER() {
                return zdocser;
            }

            /**
             * Sets the value of the zdocser property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCSER(String value) {
                this.zdocser = value;
            }

            /**
             * Gets the value of the zdocnum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZDOCNUM() {
                return zdocnum;
            }

            /**
             * Sets the value of the zdocnum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZDOCNUM(String value) {
                this.zdocnum = value;
            }

            /**
             * Gets the value of the adr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getADR() {
                return adr;
            }

            /**
             * Sets the value of the adr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setADR(String value) {
                this.adr = value;
            }

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPHONE() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPHONE(String value) {
                this.phone = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEMAIL() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEMAIL(String value) {
                this.email = value;
            }

			@Override
			public String toString() {
				StringBuilder builder = new StringBuilder();
				builder.append("ZSV [zi=");
				builder.append(zi);
				builder.append(", zf=");
				builder.append(zf);
				builder.append(", zo=");
				builder.append(zo);
				builder.append(", zdr=");
				builder.append(zdr);
				builder.append(", zenp=");
				builder.append(zenp);
				builder.append(", zsmo=");
				builder.append(zsmo);
				builder.append(", zdoctype=");
				builder.append(zdoctype);
				builder.append(", zdocser=");
				builder.append(zdocser);
				builder.append(", zdocnum=");
				builder.append(zdocnum);
				builder.append(", adr=");
				builder.append(adr);
				builder.append(", phone=");
				builder.append(phone);
				builder.append(", email=");
				builder.append(email);
				builder.append("]");
				return builder.toString();
			}

        }


		@Override
		public String toString() {
			StringBuilder builder = new StringBuilder();
			builder.append("IRP [ntype=");
			builder.append(ntype);
			builder.append(", irptype=");
			builder.append(irptype);
			builder.append(", datecreate=");
			builder.append(datecreate);
			builder.append(", timecreate=");
			builder.append(timecreate);
			builder.append(", way=");
			builder.append(way);
			builder.append(", how=");
			builder.append(how);
			builder.append(", theme=");
			builder.append(theme);
			builder.append(", otvt=");
			builder.append(otvt);
			builder.append(", otvkon=");
			builder.append(otvkon);
			builder.append(", employee1=");
			builder.append(employee1);
			builder.append(", zsv=");
			builder.append(zsv);
			builder.append(", insv=");
			builder.append(insv);
			builder.append(", dataplan=");
			builder.append(dataplan);
			builder.append(", dateclose=");
			builder.append(dateclose);
			builder.append(", result=");
			builder.append(result);
			builder.append("]");
			return builder.toString();
		}

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="DATA" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="MONTH" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="DAY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="SMO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "data",
        "year",
        "month",
        "day",
        "smo",
        "filename"
    })
    public static class ZGLV {

        @XmlElement(name = "VERSION")
        protected float version;
        @XmlElement(name = "DATA", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar data;
        @XmlElement(name = "YEAR")
        protected short year;
        @XmlElement(name = "MONTH")
        protected byte month;
        @XmlElement(name = "DAY")
        protected byte day;
        @XmlElement(name = "SMO")
        protected int smo;
        @XmlElement(name = "FILENAME", required = true)
        protected String filename;

        /**
         * Gets the value of the version property.
         * 
         */
        public float getVERSION() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         */
        public void setVERSION(float value) {
            this.version = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATA() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATA(XMLGregorianCalendar value) {
            this.data = value;
        }

        /**
         * Gets the value of the year property.
         * 
         */
        public short getYEAR() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         */
        public void setYEAR(short value) {
            this.year = value;
        }

        /**
         * Gets the value of the month property.
         * 
         */
        public byte getMONTH() {
            return month;
        }

        /**
         * Sets the value of the month property.
         * 
         */
        public void setMONTH(byte value) {
            this.month = value;
        }

        /**
         * Gets the value of the day property.
         * 
         */
        public byte getDAY() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         */
        public void setDAY(byte value) {
            this.day = value;
        }

        /**
         * Gets the value of the smo property.
         * 
         */
        public int getSMO() {
            return smo;
        }

        /**
         * Sets the value of the smo property.
         * 
         */
        public void setSMO(int value) {
            this.smo = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFILENAME() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFILENAME(String value) {
            this.filename = value;
        }

		@Override
		public String toString() {
			StringBuilder builder = new StringBuilder();
			builder.append("ZGLV [version=");
			builder.append(version);
			builder.append(", data=");
			builder.append(data);
			builder.append(", year=");
			builder.append(year);
			builder.append(", month=");
			builder.append(month);
			builder.append(", day=");
			builder.append(day);
			builder.append(", smo=");
			builder.append(smo);
			builder.append(", filename=");
			builder.append(filename);
			builder.append("]");
			return builder.toString();
		}

		

    }


	@Override
	public String toString() {
		return "IRPLIST [zglv=" + zglv + ", irp=" + irp + "]";
	}

}
